package models

import "time"

type PenilaianAwalKeperawatanKebidanan struct {
	NoRawat         string    `gorm:"column:no_rawat;primaryKey"`
	Tanggal         time.Time `gorm:"column:tanggal"`
	Informasi       string    `gorm:"column:informasi"`
	Td              string    `gorm:"column:td"`
	Nadi            string    `gorm:"column:nadi"`
	Rr              string    `gorm:"column:rr"`
	Suhu            string    `gorm:"column:suhu"`
	Gcs             string    `gorm:"column:gcs"`
	Bb              string    `gorm:"column:bb"`
	Tb              string    `gorm:"column:tb"`
	Lila            string    `gorm:"column:lila"`
	Bmi             string    `gorm:"column:bmi"`
	Tfu             string    `gorm:"column:tfu"`
	Tbj             string    `gorm:"column:tbj"`
	Letak           string    `gorm:"column:letak"`
	Presentasi      string    `gorm:"column:presentasi"`
	Penurunan       string    `gorm:"column:penurunan"`
	His             string    `gorm:"column:his"`
	Kekuatan        string    `gorm:"column:kekuatan"`
	Lamanya         string    `gorm:"column:lamanya"`
	Bjj             string    `gorm:"column:bjj"`
	KetBjj          string    `gorm:"column:ket_bjj"`
	Portio          string    `gorm:"column:portio"`
	Serviks         string    `gorm:"column:serviks"`
	Ketuban         string    `gorm:"column:ketuban"`
	Hodge           string    `gorm:"column:hodge"`
	Inspekulo       string    `gorm:"column:inspekulo"`
	KetInspekulo    string    `gorm:"column:ket_inspekulo"`
	Ctg             string    `gorm:"column:ctg"`
	KetCtg          string    `gorm:"column:ket_ctg"`
	Usg             string    `gorm:"column:usg"`
	KetUsg          string    `gorm:"column:ket_usg"`
	Lab             string    `gorm:"column:lab"`
	KetLab          string    `gorm:"column:ket_lab"`
	Lakmus          string    `gorm:"column:lakmus"`
	KetLakmus       string    `gorm:"column:ket_lakmus"`
	Panggul         string    `gorm:"column:panggul"`
	KeluhanUtama    string    `gorm:"column:keluhan_utama"`
	Umur            string    `gorm:"column:umur"`
	Lama            string    `gorm:"column:lama"`
	Banyaknya       string    `gorm:"column:banyaknya"`
	Haid            string    `gorm:"column:haid"`
	Siklus          string    `gorm:"column:siklus"`
	KetSiklus       string    `gorm:"column:ket_siklus"`
	KetSiklus1      string    `gorm:"column:ket_siklus1"`
	Status          string    `gorm:"column:status"`
	Kali            string    `gorm:"column:kali"`
	Usia1           string    `gorm:"column:usia1"`
	Ket1            string    `gorm:"column:ket1"`
	Usia2           string    `gorm:"column:usia2"`
	Ket2            string    `gorm:"column:ket2"`
	Usia3           string    `gorm:"column:usia3"`
	Ket3            string    `gorm:"column:ket3"`
	Hpht            string    `gorm:"column:hpht"`
	UsiaKehamilan   string    `gorm:"column:usia_kehamilan"`
	Tp              string    `gorm:"column:tp"`
	Imunisasi       string    `gorm:"column:imunisasi"`
	KetImunisasi    string    `gorm:"column:ket_imunisasi"`
	G               string    `gorm:"column:g"`
	P               string    `gorm:"column:p"`
	A               string    `gorm:"column:a"`
	Hidup           string    `gorm:"column:hidup"`
	Ginekologi      string    `gorm:"column:ginekologi"`
	Kebiasaan       string    `gorm:"column:kebiasaan"`
	KetKebiasaan    string    `gorm:"column:ket_kebiasaan"`
	Kebiasaan1      string    `gorm:"column:kebiasaan1"`
	KetKebiasaan1   string    `gorm:"column:ket_kebiasaan1"`
	Kebiasaan2      string    `gorm:"column:kebiasaan2"`
	KetKebiasaan2   string    `gorm:"column:ket_kebiasaan2"`
	Kebiasaan3      string    `gorm:"column:kebiasaan3"`
	Kb              string    `gorm:"column:kb"`
	KetKb           string    `gorm:"column:ket_kb"`
	Komplikasi      string    `gorm:"column:komplikasi"`
	KetKomplikasi   string    `gorm:"column:ket_komplikasi"`
	Berhenti        string    `gorm:"column:berhenti"`
	Alasan          string    `gorm:"column:alasan"`
	AlatBantu       string    `gorm:"column:alat_bantu"`
	KetBantu        string    `gorm:"column:ket_bantu"`
	Prothesa        string    `gorm:"column:prothesa"`
	KetPro          string    `gorm:"column:ket_pro"`
	Adl             string    `gorm:"column:adl"`
	StatusPsiko     string    `gorm:"column:status_psiko"`
	KetPsiko        string    `gorm:"column:ket_psiko"`
	HubKeluarga     string    `gorm:"column:hub_keluarga"`
	TinggalDengan   string    `gorm:"column:tinggal_dengan"`
	KetTinggal      string    `gorm:"column:ket_tinggal"`
	Ekonomi         string    `gorm:"column:ekonomi"`
	Budaya          string    `gorm:"column:budaya"`
	KetBudaya       string    `gorm:"column:ket_budaya"`
	Edukasi         string    `gorm:"column:edukasi"`
	KetEdukasi      string    `gorm:"column:ket_edukasi"`
	BerjalanA       string    `gorm:"column:berjalan_a"`
	BerjalanB       string    `gorm:"column:berjalan_b"`
	BerjalanC       string    `gorm:"column:berjalan_c"`
	Hasil           string    `gorm:"column:hasil"`
	Lapor           string    `gorm:"column:lapor"`
	KetLapor        string    `gorm:"column:ket_lapor"`
	Sg1             string    `gorm:"column:sg1"`
	Nilai1          string    `gorm:"column:nilai1"`
	Sg2             string    `gorm:"column:sg2"`
	Nilai2          string    `gorm:"column:nilai2"`
	TotalHasil      string    `gorm:"column:total_hasil"`
	Nyeri           string    `gorm:"column:nyeri"`
	Provokes        string    `gorm:"column:provokes"`
	KetProvokes     string    `gorm:"column:ket_provokes"`
	Quality         string    `gorm:"column:quality"`
	KetQuality      string    `gorm:"column:ket_quality"`
	Lokasi          string    `gorm:"column:lokasi"`
	Menyebar        string    `gorm:"column:menyebar"`
	SkalaNyeri      string    `gorm:"column:skala_nyeri"`
	Durasi          string    `gorm:"column:durasi"`
	NyeriHilang     string    `gorm:"column:nyeri_hilang"`
	KetNyeri        string    `gorm:"column:ket_nyeri"`
	PadaDokter      string    `gorm:"column:pada_dokter"`
	KetDokter       string    `gorm:"column:ket_dokter"`
	Masalah         string    `gorm:"column:masalah"`
	Tindakan        string    `gorm:"column:tindakan"`
	Nip             string    `gorm:"column:nip"`
}

func (PenilaianAwalKeperawatanKebidanan) TableName() string {
	return "penilaian_awal_keperawatan_kebidanan"
}
